<header class="p-2">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="header-link-logo d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <img src="/img/logo.png" class="header-img-logo">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 header-nav-menu">
                <li class="nav-link px-2 header-nav-item-hamburguer" onclick="changeSidebar()">
                    <div></div>
                    <div></div>
                    <div></div>
                </li>
                <li><a href="/" class="nav-link px-2 active">Home</a></li>
                <li><a href="#" class="nav-link px-2">Products</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control" placeholder="Pesquisar..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#" class="d-block link-light text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small">
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>