<section class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark section-sidebar sidebar-open">
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <abbr title="Home">
                <a href="#" class="nav-link link-light active" aria-current="page">
                    <i class="fa fa-home"></i>
                    <span>Home</span>
                </a>
            </abbr>
        </li>
        <li class="nav-item">
            <abbr title="Users">
                <a href="#" class="nav-link link-light" aria-current="page">
                    <i class="fa fa-users"></i>
                    <span>Users</span>
                </a>
            </abbr>
        </li>
        
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>mdo</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Sign out</a></li>
        </ul>
    </div>
</section>
<aside class="section-asidebar sidebar-open"></aside>