<section class="h-100 gradient-form" style="background-color: #eee;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-10">
                <div class="card rounded-3 text-black">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="card-body p-md-5 mx-md-4">

                                <div class="text-center">
                                    <img src="img/logo.png" style="width: 185px;" alt="logo">
                                    <h4 class="mt-1 mb-5 pb-1">Nós Somos o MarketPlace Team</h4>
                                </div>

                                <form action="#" method="post">
                                    <p>Entre com sua Conta!!</p>

                                    <input type="hidden" name="token" value="<?php echo $this->view->token ?>">
                                    <div class="form-outline mb-4">
                                        <input type="email" id="form2Example11" class="form-control" placeholder="Email ou Usuario de login" name="login" />
                                        <label class="form-label" for="form2Example11">Login</label>
                                    </div>

                                    <div class="form-outline mb-4">
                                        <input type="password" id="form2Example22" class="form-control" placeholder="Senha" name="password" />
                                        <label class="form-label" for="form2Example22">Password</label>
                                    </div>

                                    <div class="text-center pt-1 mb-5 pb-1">
                                        <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" type="button">
                                            Entrar
                                        </button>
                                        <a class="text-muted text-decoration-none" href="#!">Esqueceu a senha?</a>
                                    </div>

                                </form>

                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                            <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                <h4 class="mb-4">Área administrativa</h4>
                                <p class="small">
                                    Acesse a área administrativa com seu login fornecido pela empresa.
                                    Faça controle de estoque, vendas, preços... Tudo pelo nosso sistema
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>